type: object
properties:
  _id:
    type: string
    example: 5c9ddd7469565200646fbeew
  name:
    type: string
    example: Single
  tracks:
    type: object
    properties:
      min:
        type: number
        example: 7
      max:
        type: number
        example: 100
  createdAt:
    type: string
    example: '2018-08-09T18:31:42Z'
  updatedAt:
    type: string
    example: '2018-08-09T18:31:42Z'
