get:
  tags:
  - Admin
  summary: Return product by id. Only accessible by support users
  parameters:
  - $ref: '#/components/parameters/authorization'
  - $ref: '#/components/parameters/idPathParam'
  - $ref: '#/components/parameters/fieldsParam'
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
put:
  tags:
  - Admin
  summary: Update product by id related to the contract
  parameters:
  - $ref: '#/components/parameters/authorization'
  - $ref: '#/components/parameters/idPathParam'
  requestBody:
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/Product"
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
delete:
  tags:
  - Admin
  summary: Delete product by id related to the contract
  parameters:
  - $ref: '#/components/parameters/authorization'
  - $ref: '#/components/parameters/idPathParam'
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateUpdateResponse"
